services:
  - type: web
    name: dg-danagemz
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn danagemz_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: danagemz_project.settings
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '0.0.0.0,127.0.0.1'
      - key: SECRET_KEY
        generator: secret
      - key: DATABASE_URL
        value: postgres://render:password@localhost:5432/db
      - key: CLOUDINARY_URL
        value: ''
      - key: DJANGO_SUPERUSER_USERNAME
        value: 'admin'
      - key: DJANGO_SUPERUSER_EMAIL
        value: 'admin@example.com'
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 'ChangeMe123!'
    healthCheckPath: / 
    autoDeploy: true
    staticPublishPath: staticfiles
